import { Mulish } from "next/font/google";
import "./globals.css";
import Header from "@/conponents/Header";



const mulish = Mulish({
  subsets: ["latin"],
  weight: ["300","400","500","600","700","800","900"], 
});

export const metadata = {
  title: "SARA Constructions",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={mulish.className}
      >
        {children}
         
        <Header />
       
      </body>
    </html>
  );
}
